steps:
  - name: 'gcr.io/cloud-builders/docker'
    # Use the SAME name here as you do in the images section below
    args: ['build', '-t', 'gcr.io/projectforpoc-489612/gkedeploymenttest:$COMMIT_SHA', '.']

images:
  # Cloud Build will now find this image and push it automatically
  - 'gcr.io/projectforpoc-489612/gkedeploymenttest:$COMMIT_SHA'

serviceAccount: 'projects/projectforpoc-489612/serviceAccounts/shamim-service-account@projectforpoc-489612.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY